job_id: job_0003
task_id: task_0001
job_type: paddle_fl
role: promoter
member_id: master1
callback_url: https://www.baidu.com
job_config:
  program: paddle_clas
  proposal_wait_time: 5
  worker_num: 2
  local_worker_num: 2
  local_trainerid_start: 0
  local_trainerid_end: 2
  max_iter: 10
  inner_step: 10
  device: cpu
  use_vdl: true
  server_endpoint: 127.0.0.1:12000
  aggregator_endpoint: 127.0.0.1:12001
  aggregator_assignee: worker2
algorithm_config: ./cnn.yml
